# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [29]:
import numpy as np
import os
rn = np.random.rand(100)

nomefold = "ex5folder"
dirname = os.path.join(os.path.abspath(os.getcwd()),nomefold)
if not os.path.exists(dirname):
    os.mkdir(dirname)
filename = os.path.join(dirname,"simple_data.txt")
np.savetxt(filename,rn)
print(np.loadtxt(filename))

[0.01772143 0.78311595 0.99837419 0.55023074 0.44365333 0.76570633
 0.37066978 0.96407657 0.77929246 0.95321277 0.66326148 0.27106253
 0.49318344 0.66089083 0.68853403 0.3278951  0.60564881 0.53552897
 0.67661982 0.94180159 0.82008751 0.9595012  0.63346338 0.35475398
 0.37088806 0.38967133 0.41457262 0.60739627 0.5973557  0.92156141
 0.51134839 0.69951571 0.28576541 0.58671494 0.31530441 0.10435255
 0.0819746  0.99931328 0.26957889 0.53194712 0.44372487 0.82489058
 0.63449333 0.14553929 0.01119319 0.78484066 0.54110113 0.58546658
 0.03749049 0.52060901 0.10366797 0.9249019  0.97819116 0.47942061
 0.96431433 0.87030347 0.72933605 0.82237974 0.75803401 0.83833736
 0.90836398 0.74362797 0.89712337 0.1864039  0.06976325 0.76454364
 0.16655806 0.95294982 0.89414656 0.82157535 0.52313782 0.1372346
 0.7924419  0.37218049 0.70008382 0.85685841 0.98652178 0.11044424
 0.23975398 0.41680991 0.61652695 0.03728645 0.52214001 0.48757219
 0.34550049 0.04421412 0.18904772 0.85199113 0.54817093 0.01539

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [30]:
r5x5 = np.random.rand(5,5)

nomefold = "ex5folder"
dirname = os.path.join(os.path.abspath(os.getcwd()),nomefold)
if not os.path.exists(dirname):
    os.mkdir(dirname)
filename = os.path.join(dirname,"data.txt")
np.savetxt(filename,r5x5)

print(np.loadtxt(filename))

[[0.87983076 0.72996386 0.41675706 0.25558373 0.5668543 ]
 [0.70371556 0.31469572 0.15801654 0.01483768 0.86527032]
 [0.42414985 0.62095548 0.14029785 0.40688361 0.8749402 ]
 [0.66111907 0.38176799 0.1488397  0.13078092 0.93299155]
 [0.2029103  0.53105605 0.68336289 0.06118754 0.75106342]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [56]:
import numpy as np
import csv
import os

# Carica il file txt
load = np.loadtxt(filename)

# Nuovo file CSV
newfilename = os.path.join(dirname, "file_transformed.csv")

# Scrivi il CSV correttamente
with open(newfilename, "w", newline='') as f:
    writer = csv.writer(f, delimiter=",")
    for row in load:
        writer.writerow(row)

# Ricarica il CSV per verificarlo
print(np.loadtxt(newfilename, delimiter=","))


[[0.87983076 0.72996386 0.41675706 0.25558373 0.5668543 ]
 [0.70371556 0.31469572 0.15801654 0.01483768 0.86527032]
 [0.42414985 0.62095548 0.14029785 0.40688361 0.8749402 ]
 [0.66111907 0.38176799 0.1488397  0.13078092 0.93299155]
 [0.2029103  0.53105605 0.68336289 0.06118754 0.75106342]]


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.